### ISSUE TITLE
getting profiler working on 2.2

### ISSUE THREAD

**Issue by mgkimsal** [tomdcc/grails-miniprofiler#3]
I know it's not your plugin exactly, but I got this working on Grails 2.2 this morning by modifying the profiler plugin as depicted in the attached file.

In the main plugin file, add some ? to beanConfig and beanDefinition on line 85 (and I think on 86/87 just to be safe?)

then in the 'else' section below that, add a 'if(beanConfig)' block to skip that code if the beanConfig is null.

![Screen shot 2012-12-22 at 1 11 34 PM](https://f.cloud.github.com/assets/75154/28618/62e0d6ac-4c63-11e2-8dce-58f852c173b0.png)

The profiler plugin is not on github or in any version control I can submit a patch to.  :/

**Comment by cdeszaq** [comment]
+1 Thanks @mgkimsal for posting the fix. I've [opened a JIRA ticket](http://jira.grails.org/browse/GPPROFILER-9) to get the profiler code moved to GitHub so that others can participate, and I've linked this fix to the [case for the profiler being broken in Grails v2.2](http://jira.grails.org/browse/GPPROFILER-8).

**Comment by tomdcc** [comment]
Hi guys. The code for the grails profiler plugin lives here: https://github.com/pledbrook/grails-profiler and I've already submitted a pull request which does more or less what you have done here https://github.com/pledbrook/grails-profiler/pull/1

Was waiting for it to be applied before closing this issue.

**Comment by mgkimsal** [comment]
Oh weird - I didn't see that.  I was looking in the /grails github and didn't see it there.  Hopefully Peter will add that patch and get everything updated.  I'd have submitted it myself but didn't know where too.  The grails.org/plugins page for profiler should have the 'source' link updated too.

**Comment by tomdcc** [comment]
Peter Ledbrook has merged the issue but not released the profiler plugin since then. In the meantime, you can build it from github and it will work fine.
